using ShutIKrol.Database;
using System.Linq;
using System.Windows;
using System.Windows.Controls;

namespace ShutIKrol.Views.Pages
{
    public partial class AddToListDialog : Window
    {
        private readonly int _bookId;

        public AddToListDialog(int bookId)
        {
            InitializeComponent();
            _bookId = bookId;
        }

        private void BtnSave_Click(object sender, RoutedEventArgs e)
        {
            if (!(CmbStatus.SelectedItem is ComboBoxItem item)) return;
            var statusId = int.Parse(item.Tag.ToString());
            var userId = Session.CurrentUser.Id;

            var db = Core.Context;

            var status = db.ReadStatuses.FirstOrDefault(rs => rs.Id == statusId);
            if (status == null)
            {
                string[] names = { "", "В планах", "Читаю", "Прочитано", "Заброшено" };
                var name = (statusId >= 1 && statusId < names.Length) ? names[statusId] : $"Статус {statusId}";

                status = new ReadStatuses { Name = name };
                db.ReadStatuses.Add(status);
                db.SaveChanges();

                // Use the Id generated by the database for the new status
                statusId = status.Id;
            }

            var existing = db.ReadList.FirstOrDefault(rl => rl.UserId == userId && rl.BookId == _bookId);
            if (existing != null)
            {
                existing.StatusId = statusId;
            }
            else
            {
                db.ReadList.Add(new ReadList { UserId = userId, BookId = _bookId, StatusId = statusId });
            }

            db.SaveChanges();
            MessageBox.Show("Книга добавлена в список!");
            this.Close();
        }
    }
}