//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pomogitee_423
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerHistory
    {
        public int Id { get; set; }
        public int Day { get; set; }
        public int DetailsNeeded { get; set; }
        public decimal RepairPrice { get; set; }
        public string Status { get; set; }
        public decimal Earnings { get; set; }
        public int DetailId { get; set; }
    
        public virtual Details Details { get; set; }
    }
}
