//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pomogitee_423
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int Id { get; set; }
        public int DetailId { get; set; }
        public decimal Cost { get; set; }
        public int DeliveryIn { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int Quantity { get; set; }
    
        public virtual Details Details { get; set; }
    }
}
