//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutIKrol.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapters
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    
        public virtual Books Books { get; set; }
    }
}
